config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts
  resources :users , only: [:show, :new, :create]
  resources :sessions , only: [:new, :create, :destroy]
  resources :comments ,only: [:create]
  resources :likes, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
#comment model
class Comment < ApplicationRecord
    #this is a polymorphic association, a comment can belong to either a post or another comment(as a reply), here commentable refers to either post or comment
    belongs_to :commentable, polymorphic: true

    # a comment can have infact many comments i.e replies
    has_many :comments, as: :commentable

    # a comment belongs to a user
    belongs_to :user
end

app/models/like.rb
#like model
class Like < ApplicationRecord
    #a like belongs to a user
    belongs_to :user
    #a like belongs to a post
    belongs_to :post
end

app/models/post.rb
#post model
class Post < ApplicationRecord
    #each page is allowed two posts, this is for (will_paginate gem)
    self.per_page = 2

    #a post has an attached image
    has_one_attached:image
    #a post has many comments, the post is in this association as commentables, and once a post is destroyed, all the comments associated with that posts are destroyed as well
    has_many :comments, as: :commentable, dependent: :destroy

    #a post has many likes
    has_many :likes, dependent: :destroy
    #a post belongs to a user
    belongs_to :user

    #the caption for the post is required and should be of minimum length 3
    validates :caption, presence: true, length: { minimum: 3 }
    #the image is also required
    validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    #a user has many posts
    has_many :posts

    #a user has many likes
    has_many :likes
    
    #a user has many comments
    has_many :comments

    #a user has a user page
    has_one_attached:avatar

    #validations added
    validates :username, presence: true, uniqueness: true
    validates :password, presence: true, length: { minimum: 8 }
    validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?, :current_user

    #this method returns the current user in the session, if any?
    def current_user
        if session[:user_id]
            @user = User.find(session[:user_id])
        end
    end

    #checks if the user is logged in
    def logged_in?
        !!current_user
    end

    #this view authorized users to make request to a path
    def authorized 
        #if the user is not authorized, redirect to signup page
        redirect_to new_user_path unless logged_in?
    end
end

app/controllers/comments_controller.rb
# a controller to mainatain comment functionality
class CommentsController < ApplicationController
    def create
        #we need to create a comment
        #we basically need a commentable id to save this post, the post obviously belongs to a user and thus the comment would indirectly belong to a user
        #to find the commentable, which can either be a post or a comment itself(in case of replies), we can use the params hash
        @new_comment = current_user.comments.build(comment_params)
        if @new_comment.save 
            #if the comment is saved successfully redirect to the timeline again
            redirect_to root_path
        else
            #if the comment is not saved due to some error, again redirect to the root_path
            redirect_to root_path
        end
    end

    private
    #a private helper method to strictly take only required parameters from params hash
    def comment_params
        params.require(:comment).permit(:body,:commentable_id, :commentable_type)
    end
end

app/controllers/likes_controller.rb
#a controller to handle likes 
class LikesController < ApplicationController
    #this is a helper method that runs before the creation of a like
    before_action :already_liked?

    #this action creates a new like
    def create
        #if an old like is present in the database for the same user and the same post, then delete that like
        if @old_like
            Like.destroy(@old_like.id)
        else
            #if there is no like prior to this, then create a new like 
            @new_like = current_user.likes.build(post_id: params[:post_id])
            #save the like to the database
            @new_like.save
        end
        #redirect user to the root_path
        redirect_to root_path
    end

    private
    #this is a helper method that checks if a like already exists for the current user and the given post
    def already_liked?
        @old_like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    end
end

app/controllers/posts_controller.rb
#controller to manage all the posts
class PostsController < ApplicationController
  #this ensures that the user should be allowed any post related activity once he is logged in
  before_action :authorized

  def index
    #fetch all the posts
    #first the posts should be sorted according to the time they were created
    @posts = Post.paginate(page: params[:page]).order([:created_at]).reverse_order
    #also passed an empty post object for the form present in the timeline
    @post = Post.new
  end

  def show
    #to show a Post
    @post = Post.find(params[:id])
  end

  def create
    #create a new Post
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to root_path
    else
      @posts = Post.paginate(page: params[:page]).order([:created_at]).reverse_order
      render :index
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    #update an existing Post
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    #destory an existing Post
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:caption, :image)
  end
end

app/controllers/sessions_controller.rb
# a controller to maintain sessions functionality (login)
class SessionsController < ApplicationController
    #creates a new session for the user, i.e logs in the user
    def create
        #fetches the user object by the username specified in the params hash
        @user = User.find_by(username: params[:session][:username])
        #if the user exists and the password entered by the user is correct, then grant him access and create a new session
        if @user and @user.authenticate(params[:session][:password])
            session[:user_id] = @user.id
            #redirect him to the timeline view
            redirect_to root_url
        else
            #if there exists any validation error, reflect via flash message
            flash.now[:error] = "Invalid email/password combination "
            #redirect again to the login page
            redirect_to new_session_path
        end
    end

    #destorys an existing session
    def destroy
        session[:user_id] = nil
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
#user controller manages the users of the application
class UsersController < ApplicationController
    #before the show action, we need to make sure that the user is logged in first, the authorized helper is defined in application_controller.rb
    before_action :authorized, only: [:show]

    #displays the profile for the user
    def show
        #fetches the user from the id in hash
        @user = User.find(params[:id])
        #only passes the posts of that user to the view
        @posts = @user.posts.all
    end

    #displays the registration form
    def new
        #passes an empty user object
        @user = User.new
    end

    #creates a new user
    def create
        #creates a new user from the user params
        @user = User.create(user_params)
        if @user.save
            #if the user is saved successfully, redirect to the timeline view
            redirect_to root_path
        else
            #otherwise render another form, and display the validation errors
            render :new
        end
    end

    privates
    def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation, :avatar)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_comment.html.erb
<!-- this partial is for rendering comment -->
<li>
    <div class="user mr-2">
        <% if User.find(comment.user_id).avatar.attached? %>
        <img src="<%= (url_for(User.find(comment.user_id).avatar))%>" alt="..." />
        <% else %>
        <img src="nouser.jpg" alt="">
        <% end %>
    </div>
    <!-- displaying the actual comment with the username -->
    <strong> <%= User.find(comment.user_id).username %> - </strong>
    <%= comment.body%>

    <!-- a form for submitting a reply -->
    <%= form_for Comment.new, class: "form-inline" do |f| %>
    <div class="input-group mb-2 mr-sm-2">
        <div class="user mr-2">
            <% if current_user.avatar.attached? %>
            <img src="<%= (url_for(current_user.avatar))%>" alt="..." />
            <% else %>
            <img src="nouser.jpg" alt="">
            <% end %>
        </div>
        <%= f.hidden_field :commentable_id, value: comment.id %>
        <%= f.hidden_field :commentable_type, value: "Comment" %>
        <%= f.text_field :body, placeholder: "Add a reply ", class: "form-control mb-2 mr-sm-2"%>
        <%= f.submit "reply", class: "btn btn-primary mb-2 rounded-corner"%>
    </div>
    <% end %>
    <!-- in a recursive manner, call out for all the comments associated with this comment -->
    <ul style="list-style: none;">
        <%= render partial: 'comment', collection: comment.comments %>
    </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Photogram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div id="content" class="content content-full-width">
                    <!-- navigation bar -->
                    <div class="py-2">
                        <ul class="profile-header-tab nav nav-tabs">
                            <li><%= link_to  "HOME", root_path, class: "nav-link" %></li>
                            <% if logged_in? %>
                                <li><%= link_to  "PROFILE", user_path(current_user), class: "nav-link" %></li>
                                <li><%= link_to "LOGOUT", session_path(current_user), method: :delete ,class: "nav-link"%></li>
                            <% end %>
                        </ul>
                    </div>
                    <%= yield %>
                </div>
            </div>
        </div>
    </div>
</body>
</html>s

app/views/posts/_comment.html.erb
<li>
    <div class="user mr-2">
        <% if User.find(comment.user_id).avatar.attached? %>
        <img src="<%= (url_for(User.find(comment.user_id).avatar))%>" alt="..." />
        <% else %>
        <img src="nouser.jpg" alt="">
        <% end %>
    </div>
    <strong> <%= User.find(comment.user_id).username %> - </strong>
    <%= comment.body%>
    <%= form_for Comment.new, class: "form-inline" do |f| %>
    <div class="input-group mb-2 mr-sm-2">
        <div class="user mr-2">
            <% if User.find(comment.user_id).avatar.attached? %>
            <img src="<%= (url_for(User.find(comment.user_id).avatar))%>" alt="..." />
            <% else %>
            <img src="nouser.jpg" alt="">
            <% end %>
        </div>
        <%= f.hidden_field :commentable_id, value: comment.id %>
        <%= f.hidden_field :commentable_type, value: "Comment" %>
        <%= f.text_field :body, placeholder: "Add a reply ", class: "form-control mb-2 mr-sm-2"%>
        <%= f.submit "reply", class: "btn btn-primary mb-2 rounded-corner"%>
    </div>
    <% end %>
    <ul style="list-style: none;">
        <%= render partial: 'comment', collection: comment.comments %>
    </ul>
</li>

app/views/posts/_form.html.erb
<!-- form for creating a new post, also for editing it -->
<%= form_for post do |f| %>
    <% if post.errors[:caption].any? %><span id="error"><%= post.errors[:caption][0] %></span><% end %>
    <%= f.text_field :caption , class: "form-control mb-2 mr-sm-2" ,placeholder: "caption" %>

    <% if post.errors[:image].any? %><span id="error"><%= post.errors[:image][0] %></span><% end %>
    <div class="input-group mb-2 mr-sm-2">
        <div class="custom-file">
            <%= f.file_field :image , class: "custom-file-input" , id: "customFile"%>
            <label class="custom-file-label" for="customFile">Choose file</label>
        </div>
    </div>
    <%= f.submit "Post",class: "mb-2 btn btn-dark" %>
<% end %>

app/views/posts/_post.html.erb
<!-- this renders out a single post -->
<li>
    <!-- begin timeline-body -->
    <div class="timeline-body">
        <div class="timeline-header">
            <!-- displays the image of the user who has posted -->
            <span class="userimage">
                <% if User.find(post.user_id).avatar.attached? %>
                <img src="<%= (url_for(User.find(post.user_id).avatar))%>" alt="..." />
                <% else %>
                <img src="nouser.jpg" alt="">
                <% end %>
            </span>
            <!-- displays the username of the user -->
            <span class="username"><%= User.find(post.user_id).username %><small></small></span>
        </div>
        <div class="timeline-content">
            <!-- relevant post details -->
            <h6><%= post.caption %></h6>
            <hr/>
            <img src="<%= (url_for(post.image))%>" ,class="img-thumbnail rounded mr-3" alt="..." width="100%" height="auto">
        </div>
        <div class="timeline-likes">
            <div class="stats-right">
                <span class="stats-text"><%= post.comments.count %> Comments</span>
            </div>
            <div class="stats">
                <span class="fa-stack fa-fw stats-icon">
                    <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <i class="fa fa-thumbs-up fa-stack-1x fa-inverse"></i>
                </span>
                <span class="stats-total"><%= post.likes.count %></span>
            </div>
        </div>
        <div class="timeline-footer">
            <i class="fa fa-thumbs-up fa-fw fa-lg m-r-3"></i>
            <%= link_to  "Like", likes_path(:post_id => post.id), method: :post ,class: "mr-3" %>
            <i class="fa fa-pencil-square-o fa-fw fa-lg m-r-3 "></i>
            <%= link_to "Edit", edit_post_path(post.id), class: "m-r-15 text-inverse-lighter" %>
        </div>
        <div class="timeline-comment-box">
            <!-- a form to add a new comment -->
            <%= form_for Comment.new, class: "form-inline" do |f| %>
                <div class="input-group mb-2 mr-sm-2">
                    <div class="user mr-2">
                        <% if current_user.avatar.attached? %>
                            <img src="<%= (url_for(current_user.avatar))%>" alt="..." />
                        <% else %>
                            <img src="nouser.jpg" alt="">
                        <% end %>
                    </div>
                    <%= f.hidden_field :commentable_id, value: post.id %>
                    <%= f.hidden_field :commentable_type, value: "Post" %>
                    <%= f.text_field :body, placeholder: "Add a Comment ", class: "form-control mb-2 mr-sm-2"%>
                    <%= f.submit "comment", class: "btn btn-primary mb-2 rounded-corner"%>
                </div>
            <% end %>
            <!-- render the all the comments related to this post -->
            <ul style= "list-style: none;"><%= render partial: 'comment', collection: post.comments %></ul>
        </div>
        <!-- end timeline-body -->
</li>

app/views/posts/edit.html.erb
<!-- this is view for editing the posts, renders the form partial -->
<%= render partial: "form", locals: { post: @post }%>

app/views/posts/index.html.erb
<!-- begin posts-content -->
<div class="profile-content">
    <div class="tab-content p-0">
        <div class="tab-pane fade active show" id="profile-post">
            <!-- begin timeline for the posts -->

            <!-- bootstrap inline form to create new posts -->
            <%= render partial: "form", locals: { post: @post }%>
            <ul class="timeline my-5">
                <!-- individual posts -->
                <div class="container" id="posts">
                    <%= render partial:"post", collection: @posts %>
                </div>
            </ul>
        </div>
    </div>
</div>

<!-- infintie scrolling -->
<div id="infinite-scrolling">
    <%= will_paginate @posts %>
</div>

app/views/posts/index.js.erb
$('#posts').append('<%= j render @posts %>');
    <% if @posts.next_page %>
       $('.pagination').replaceWith('<%= j will_paginate @posts %>');
    <% else %>
       $(window).off('scroll');
       $('.pagination').remove();
    <% end %>

app/views/users/new.html.erb
<div class="container">
    <!-- user registration form -->
    <div class="card bg-light">
        <article class="card-body mx-auto" style="max-width: 400px;">
            <h4 class="card-title mt-3 text-center">Create Account</h4>
            <p class="text-center">Get started with your free account</p>
            <%= form_for @user do |f| %>
            <% if @user.errors[:username].any? %><span id="error"><%= @user.errors[:username][0] %></span><% end %>
            <div class="form-group input-group">
                <%= f.text_field :username , class: "form-control mb-2 mr-sm-2" ,placeholder: "username" %>
            </div>
            <% if @user.errors[:email].any? %><span id="error"><%= @user.errors[:email][0] %></span><% end %>
            <div class="form-group input-group">
                <%= f.email_field :email , class: "form-control mb-2 mr-sm-2" ,placeholder: "email" %>
            </div>
            <% if @user.errors[:password].any? %><span id="error"><%= @user.errors[:password][0] %></span><% end %>
            <div class="form-group input-group">
                <%= f.password_field :password , class: "form-control mb-2 mr-sm-2" ,placeholder: "password" %>
            </div>
            <% if @user.errors[:password_confirmation].any? %><span id="error"><%= @user.errors[:password_confirmation][0] %></span><% end %>
            <div class="form-group input-group">
                <%= f.password_field :password_confirmation , class: "form-control mb-2 mr-sm-2" ,placeholder: "confirm password" %>
            </div>
            <div class="input-group mb-2 mr-sm-2">
                <div class="custom-file">
                    <%= f.file_field :avatar , class: "custom-file-input" , id: "customFile"%>
                    <label class="custom-file-label" for="customFile">Choose Profile Photo</label>
                </div>
            </div>
            <div class="form-group">
                <%= f.submit  "Create Account", class: "btn btn-primary" %>
            </div>
            <% end %>
            <p class="text-center">Have an account? <%= link_to  "Log In", new_session_path %></p>
        </article>
    </div> <!-- card.// -->

</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div id="content" class="content content-full-width">
                <!-- begin profile -->
                <div class="profile">
                    <div class="profile-header">
                        <div class="profile-header-cover"></div>
                        <div class="profile-header-content">
                            <div class="profile-header-img">
                                <% if @user.avatar.attached? %>
                                <img src="<%= (url_for(@user.avatar))%>" alt="..." />
                                <% else %>
                                <img src="/nouser.jpg" alt="">
                                <% end %>
                            </div>
                            <div class="profile-header-info">
                                <h4 class="m-t-10 m-b-5"><%= @user.username %></h4>
                                <p class="m-b-10"><%= @user.email %></p>
                                <!-- here the option will be given to edit the profile -->
                                <a href="#" class="btn btn-xs btn-yellow">Edit Profile</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <ul class="timeline my-5">
            <!-- individual posts -->
            <div class="container" id="posts">
                <%= render partial:"posts/post", collection: @posts %>
            </div>
        </ul>
    </div>
</div>